// ─── MOCK DATA PLASTIUSOS ───────────────────────────────────────────────────
// Usado en todas las vistas mientras el backend no está listo

export const PUNTOS_RECOLECCION = [
  {
    id: 1,
    nombre: "EcoPoint Centro Histórico",
    direccion: "Calle 5 #4-36, Centro Histórico",
    latitud: 2.4419,
    longitud: -76.6073,
    activo: true,
    horario: "Lun-Sáb 8am-6pm",
    tiposPlastico: ["Botellas PET", "Tapas plásticas", "Envases HDPE"],
    materiales: ["Plástico", "Vidrio", "Cartón"],
    nivelLlenado: 65,
    encargado: "Carlos López",
    telefono: "+57 300 123 4567",
  },
  {
    id: 2,
    nombre: "ReciclaVerde Bolívar",
    direccion: "Carrera 7 #15-20, Barrio Bolívar",
    latitud: 2.456,
    longitud: -76.6012,
    activo: true,
    horario: "Lun-Dom 7am-8pm",
    tiposPlastico: ["Botellas PET", "Bolsas plásticas", "Film plástico"],
    materiales: ["Plástico", "Papel", "Electrónicos"],
    nivelLlenado: 30,
    encargado: "Ana Torres",
    telefono: "+57 301 234 5678",
  },
  {
    id: 3,
    nombre: "PuntoEco La Esmeralda",
    direccion: "Av. Circunvalar #40-12, La Esmeralda",
    latitud: 2.427,
    longitud: -76.5983,
    activo: true,
    horario: "Mar-Dom 9am-5pm",
    tiposPlastico: ["Botellas PET", "Vidrio reciclable", "Latas metálicas"],
    materiales: ["Plástico", "Vidrio", "Metal"],
    nivelLlenado: 85,
    encargado: "Pedro Ramírez",
    telefono: "+57 302 345 6789",
  },
  {
    id: 4,
    nombre: "GreenHub Alfonso López",
    direccion: "Calle 18 #10-50, Alfonso López",
    latitud: 2.4421,
    longitud: -76.618,
    activo: false,
    horario: "Lun-Vie 8am-4pm",
    tiposPlastico: ["HDPE", "Poliestireno expandido"],
    materiales: ["Plástico", "Electrónicos"],
    nivelLlenado: 0,
    encargado: "Sandra Muñoz",
    telefono: "+57 303 456 7890",
  },
  {
    id: 5,
    nombre: "EcoStation Las Américas",
    direccion: "Carrera 9 #28-15, Las Américas",
    latitud: 2.433,
    longitud: -76.6095,
    activo: true,
    horario: "Lun-Sáb 8am-5pm",
    tiposPlastico: ["Botellas PET", "Cartón prensado", "Papel periódico"],
    materiales: ["Plástico", "Cartón", "Papel"],
    nivelLlenado: 45,
    encargado: "Luis Castro",
    telefono: "+57 304 567 8901",
  },
  {
    id: 6,
    nombre: "ReciclaPunto Tulcán",
    direccion: "Calle 25 #6-80, Barrio Tulcán",
    latitud: 2.449,
    longitud: -76.595,
    activo: true,
    horario: "Mar-Dom 8am-6pm",
    tiposPlastico: ["Botellas PET", "Cartón", "Papel periódico", "E-waste"],
    materiales: ["Plástico", "Cartón", "Papel", "Electrónicos"],
    nivelLlenado: 20,
    encargado: "Sandra Muñoz",
    telefono: "+57 305 678 9012",
  },
];

export const PRODUCTOS_CATALOGO = [
  {
    id: 1,
    nombre: "Bolsa Ecológica Reutilizable",
    descripcion: "Bolsa de tela orgánica con diseño ecológico. Ideal para compras del día a día sin usar plástico.",
    costoPuntos: 150,
    stock: 25,
    imagenUrl: "https://images.unsplash.com/photo-1764913672630-23e9fb7e6836?w=400&q=80",
    categoria: "Hogar",
    activo: true,
  },
  {
    id: 2,
    nombre: "Botella Termo Acero Inox.",
    descripcion: "Termo de 500ml que mantiene bebidas frías 24h y calientes 12h. Libre de BPA.",
    costoPuntos: 450,
    stock: 10,
    imagenUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
    categoria: "Cocina",
    activo: true,
  },
  {
    id: 3,
    nombre: "Kit Cubiertos de Bambú",
    descripcion: "Set de cuchara, tenedor y cuchillo elaborados en bambú 100% sostenible.",
    costoPuntos: 200,
    stock: 18,
    imagenUrl: "https://images.unsplash.com/photo-1584265549884-8b11f04d1b24?w=400&q=80",
    categoria: "Cocina",
    activo: true,
  },
  {
    id: 4,
    nombre: "Planta de Interior Suculenta",
    descripcion: "Suculenta decorativa en maceta biodegradable. Fácil de cuidar, perfecta para oficinas.",
    costoPuntos: 100,
    stock: 30,
    imagenUrl: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&q=80",
    categoria: "Jardín",
    activo: true,
  },
  {
    id: 5,
    nombre: "Cuaderno Papel Reciclado",
    descripcion: "Cuaderno A5 con 100 hojas de papel reciclado certificado. Tapa dura.",
    costoPuntos: 80,
    stock: 50,
    imagenUrl: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&q=80",
    categoria: "Oficina",
    activo: true,
  },
  {
    id: 6,
    nombre: "Kit Cepillos de Dientes Bambú",
    descripcion: "Pack x4 cepillos de bambú biodegradable con cerdas de carbón activado.",
    costoPuntos: 120,
    stock: 40,
    imagenUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&q=80",
    categoria: "Cuidado Personal",
    activo: true,
  },
  {
    id: 7,
    nombre: "Jabón Artesanal Ecológico",
    descripcion: "Jabón natural elaborado con aceites esenciales y sin parabenos. Sin empaque plástico.",
    costoPuntos: 90,
    stock: 35,
    imagenUrl: "https://images.unsplash.com/photo-1604405051014-33bbd6c33f1d?w=400&q=80",
    categoria: "Cuidado Personal",
    activo: true,
  },
  {
    id: 8,
    nombre: "Semillas Kit Huerta Urbana",
    descripcion: "Set de 6 variedades de semillas orgánicas certificadas para huerta en casa.",
    costoPuntos: 160,
    stock: 20,
    imagenUrl: "https://images.unsplash.com/photo-1618388991720-3f42d3d4aff7?w=400&q=80",
    categoria: "Jardín",
    activo: true,
  },
];

export const HISTORIAL_MOCK = [
  {
    id: 1,
    tipo: "entrega",
    descripcion: "Entrega en EcoPoint Centro",
    punto: { nombre: "EcoPoint Centro Histórico" },
    puntosOtorgados: 280,
    kilos: 28,
    material: "Plástico PET",
    estado: "VALIDADA",
    fechaEntrega: "2025-06-15T10:30:00",
  },
  {
    id: 2,
    tipo: "canje",
    descripcion: "Canje: Bolsa Ecológica",
    producto: { nombre: "Bolsa Ecológica Reutilizable", costoPuntos: 150 },
    estado: "entregado",
    fechaPedido: "2025-06-10T14:20:00",
  },
  {
    id: 3,
    tipo: "entrega",
    descripcion: "Entrega en ReciclaVerde Bolívar",
    punto: { nombre: "ReciclaVerde Bolívar" },
    puntosOtorgados: 150,
    kilos: 15,
    material: "Cartón",
    estado: "VALIDADA",
    fechaEntrega: "2025-06-05T09:15:00",
  },
  {
    id: 4,
    tipo: "entrega",
    descripcion: "Entrega en EcoStation Las Américas",
    punto: { nombre: "EcoStation Las Américas" },
    puntosOtorgados: 0,
    kilos: 10,
    material: "Vidrio",
    estado: "PENDIENTE",
    fechaEntrega: "2025-06-20T11:45:00",
  },
  {
    id: 5,
    tipo: "canje",
    descripcion: "Canje: Kit Cubiertos Bambú",
    producto: { nombre: "Kit Cubiertos de Bambú", costoPuntos: 200 },
    estado: "pendiente",
    fechaPedido: "2025-06-18T16:30:00",
  },
];

export const STATS_CIUDAD = {
  totalRecicladores: 1847,
  totalKgReciclados: 45230,
  totalTransacciones: 8920,
  co2Evitado: 90460,
  puntosActivos: PUNTOS_RECOLECCION.filter(p => p.activo).length,
};

export const MATERIALES = [
  { icono: "🧴", nombre: "Plástico PET", pts: 15, color: "bg-blue-100 text-blue-700" },
  { icono: "📦", nombre: "Cartón", pts: 10, color: "bg-amber-100 text-amber-700" },
  { icono: "🫙", nombre: "Vidrio", pts: 8, color: "bg-green-100 text-green-700" },
  { icono: "🥫", nombre: "Metal / Lata", pts: 20, color: "bg-gray-100 text-gray-700" },
  { icono: "📄", nombre: "Papel", pts: 5, color: "bg-yellow-100 text-yellow-700" },
  { icono: "💻", nombre: "Electrónicos", pts: 50, color: "bg-purple-100 text-purple-700" },
];
